danny-avila/rag_api

- main.py
- requirements.txt
- It's no longer necessary to share volume storage with LibreChat for the RAG API to work. File uploads will be streamed to wherever the API is setup.
- Adds another basic layer of security by not allowing users to query files not vectorized by them
- Also added more logging and typing across the main routes.
> 💽 feat: New File Uploading Strategy & Additional Security

- README.md
Short installation notes for AWS RDS
> 📖 docs: Added AWS RDS Postgres Instructions

- README.md
- config.py
- main.py
- requirements.lite.txt
- requirements.txt
- store.py
- store_factory.py
related to https://github.com/danny-avila/LibreChat/discussions/2304
So far, only two APIs work:
- `/embed`
- `/query`
They are sufficient to make most important use case of asking a questions based on a file work (see screenshot above)
> 🚀 feat: Add Atlas MongoDB as an option for Vector Store

- config.py
- main.py
- middleware.py
- models.py
- mongo.py
- requirements.lite.txt
- requirements.txt
I implemented improvements to the delete_documents endpoint and added a MongoDB health check to ensure better validation and connectivity.
- Changed the delete_documents endpoint to use a Pydantic model for better request body validation.
- Fixed the issue where the delete_documents endpoint was incorrectly using query parameters.
- Added a MongoDB health check to ensure database connectivity.
- Refactored the code to use enums for constants, improving readability and maintainability.
- swap python-jose for PyJWT due to [security advisories ](https://github.com/danny-avila/rag_api/security/dependabot/6)
- add warning that MongoDB Atlas is not querying correctly
I tested the changes locally by making DELETE requests to the delete_documents endpoint with valid and invalid request bodies to …
> 🌡️ fix: Delete Endpoint Validation, List Index Errors, use PyJWT

- .github/workflows/docker-build-workflow.yaml
- .github/workflows/images.yaml
- .github/workflows/release.yaml
This PR adds release workflow that is triggered when a tag is created and builds and image with the same  docker tag
> 🐳 feat: Release workflow for versioning docker images

- .github/workflows/docker-build-workflow.yaml
- .github/workflows/images.yaml
- .github/workflows/release.yaml
Removes debug code accidentally pushed to `main` and switch `images.yaml` workflow to use common `docker-build` workflow.
Fixes #40
> fix: Github Workflows. Remove debug code from common docker workflow

- requirements.lite.txt
This PR fixes `requirements.lite.txt` which is missing two requirements that were added in #51. Without these requirements, the "lite" version will fail when powerpoint files are submitted for processing.
**Changes**:
- Added [python-magic](https://pypi.org/project/python-magic/) and [python-pptx](https://pypi.org/project/python-pptx/) to `requirements.lite.txt`, matching the versions in `requirements.txt`.
> 🔧 fix: missing python-magic and python-pptx in requirements.lite.txt

- requirements.lite.txt
- requirements.txt
This PR adds [xlrd](https://pypi.org/project/xlrd/) to `requirements.txt` and `requirements.lite.txt`.  This fixes the following exception that is raised when an `.xls` file is submitted to the `/embed` endpoint:
> ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.
> 🔧 fix: missing xlrd requirement for .xls files

- README.md
- config.py
- requirements.txt
Added bedrock embeddings support. Need to set env variables 1) AWS_ACCESS_KEY 2) AWS_SECRET_ACCESS_KEY 3) EMBEDDINGS_PROVIDER=bedrock  and optionally 3) AWS_DEFAULT_REGION 4)EMBEDDINGS_MODEL (default: amazon.titan-embed-text-v1)
Tested using pgvector vector storage with bedrock embedding provider with model amazon.titan-embed-text-v1 through rag docker image.
1) Successfully uploaded and embedded a small text file 
2) Successfully performed query search returning relevant documents.
> 🪨 feat: AWS Bedrock embeddings support 

- requirements.lite.txt
Updated lite requirements list to better reflect requirements list: 
langchain-ollama==0.2.0
langchain-openai==0.2.0
langchain-huggingface==0.1.0
> chore: updating lite requirements to include ollama and others

- Dockerfile.lite
This reduces the "lite" docker image size by over 1GB:
```
❯ docker images | grep python-with
python-with-slim                      1                  8e2af154aac9   42 seconds ago   1.81GB
python-without-slim                   1                  f94cf64c4591   2 minutes ago    2.97GB
```
and removes about 100 vulnerabilities (See):
https://hub.docker.com/_/python/tags?name=3.10.16-slim-bookworm
https://hub.docker.com/_/python/tags?name=3.10.16-bookworm
slim is still based around glibc, so C bindings should still work
> chore: make "lite" docker image lighter

- Dockerfile
- Dockerfile.lite
- docker-compose.yaml
- main.py
- requirements.lite.txt
- requirements.txt
I enhanced error logging with traceback throughout the application, updated dependencies for `unstructured` and `langchain` core packages, adjusted Dockerfiles to pre-download NLTK data and disable Unstructured analytics, and removed the version specification from `docker-compose.yaml`.
- Added detailed error logging with traceback in `main.py` to aid in debugging and error tracking.
- Updated `unstructured` and `langchain` core packages to the latest versions in `requirements.txt` and `requirements.lite.txt`.
- Modified `Dockerfile` and `Dockerfile.lite` to download NLTK data during build time, preventing `unstructured` from downloading packages at runtime.
- Set the `NLTK_DATA` environment variable to `/app/nltk_data` in Dockerfiles for consistent NLTK data path.
- Disabled Unstructured …
> 🛠️ fix: Enhance Error Logging, Update Dependencies, and Optimize NLTK Setup

- .vscode/launch.json
- config.py
- main.py
- models.py
I added support for 'entity_id' as an alternative to 'user_id' in various endpoints, improved the handling of the 'DEBUG_RAG_API' environment variable, and updated the VSCode launch settings to include an 'envFile' configuration.
- Added `entity_id` as an alternative parameter in the `/query`, `/embed`, `/embed-upload`, and `/local/embed` endpoints to allow authorization using `entity_id` for shared resources.
- Improved `debug_mode` environment variable handling by ensuring consistent parsing of boolean values, supporting multiple truthy values like `'true'`, `'1'`, `'yes'`, etc.
- Updated exception handling to provide more detailed error responses when request validation fails.
- Updated VSCode `launch.json` to include `envFile` configuration, allowing environment variables to be loaded …
> ✨ feat: Add 'entity_id' Parameter

- app/services/database.py
- main.py
- tests/services/test_database.py
Removed unnecessary index check as mentioned in: https://github.com/danny-avila/rag_api/issues/133
Also solved the issue why index was not getting created by fixing the comparison between enum and string. This check was broken and globally whenever the startup happened the index never got created. So no pgvector db has this index and it is vital for performance
Test changes:
Removed the dummy function call for the extra if check for the index
> 🔍 fix: Creation of `custom_id` Index

- app/routes/document_routes.py
- app/services/vector_store/async_pg_vector.py
- app/services/vector_store/atlas_mongo_vector.py
- app/services/vector_store/extended_pg_vector.py
- tests/conftest.py
- tests/test_main.py
Improved query performances for pgvector db by adding filters on id as described in issue: https://github.com/danny-avila/rag_api/issues/133
Observation:
For several routes to fetch or delete file information, select all queries were made to the pgvector db without any where clause through the get_all_ids method, which was then brought in to the local memory to check if a custom_id exists. This is highly inefficient.
Outcome:
made a new get_filtered_ids method to filter directly on the pgvector db with where clause to only fetch the necessary ids.
This will highly improve performance.
> refactor: Improve query performance by adding filtered IDs

- app/config.py
This is an alternate version of https://github.com/danny-avila/rag_api/pull/150, with two differences:
- make the `chunk_size` parameter configurable using the `EMBEDDINGS_CHUNK_SIZE` parameter
- also apply this to Azure OpenAI endpoints (I'm currently running into issues there myself)
> 🪙 feat: `EMBEDDINGS_CHUNK_SIZE` parameter for Azure + OpenAI

- app/routes/document_routes.py
- tests/test_main.py
The main change is to run the document loader `loader.load` in a background thread to not block the entire event loop.
With this, other API calls can still be processed while the file loads.
We have scenarios where the `/embed` route takes so much time that it is blocking health-checks. As a result, the instance is considered unhealthy and killed before the embedding could complete.
I tested this change allows at least the `/health` route to return quickly even while the processing is ongoing.
Although only `/embed` is necessary for us, I also updated `/local/embed` and `/embed-upload`.
While testing them with `curl` I had errors with `get_loader`
```
Something went wrong : 
too many values to unpack (expected 2)
```
This is why the changes related to `file_ext` and the the removing of …
> 🚅 refactor: Implement Async Support for Embedding Routes

- app/routes/document_routes.py
- app/utils/document_loader.py
- Added  function to determine file encoding based on BOM markers.
- Introduced  function to remove temporary UTF-8 files created during encoding conversion.
- Updated CSV loading logic to handle non-UTF-8 encodings by creating temporary UTF-8 files for processing.
- Integrated cleanup functionality in embedding routes to ensure temporary files are removed after processing.
Closes #168
> 📒 feat: Support CSV loading for non-UTF-8 files

- app/routes/document_routes.py
> 🔧 fix: Handle Surrogate Character Errors When Hashing Documents

- app/routes/document_routes.py
- app/utils/document_loader.py
> 📒 fix: Ignore invalid utf-8 characters when handling PDFs

- app/services/vector_store/extended_pg_vector.py
- app/utils/document_loader.py
I improved temporary file cleanup reliability in the document loader and enhanced logging clarity for vector store operations.
- Fixed `cleanup_temp_encoding_file` to verify `_temp_filepath` is not None before attempting file removal
- Added `_sanitize_parameters_for_logging` static method to ExtendedPgVector for truncating embeddings and large values in logs
- Updated query logging to utilize sanitization, preventing verbose embedding vectors from cluttering log output
- Maintained proper handling of various parameter types including dictionaries, lists, tuples, and nested structures
Test the changes by:
1. Loading documents with various encodings to verify temporary file cleanup works correctly
2. Enabling DEBUG_PGVECTOR_QUERIES environment variable and performing vector store …
> 🔧 chore: Improve Document Loader and Vector Store Logging
